#!/bin/sh

set -e

# Include browser config
# TODO: Check that sourcing succeeds
#digabi config source browser
BROWSER_APPLICATION="$(digabi config get browser_application)"

if [ -z "${BROWSER_APPLICATION}" ]
then
	echo "E: TODO"
	# TODO: Ask user, which browser should we run?
fi

case "${BROWSER_APPLICATION}" in
	chromium)
		APP="/usr/bin/chromium"
		FLAGS="--proxy-server=${BROWSER_PROXY} ${BROWSER_HOMEPAGE}"
		;;
	iceweasel)
		APP="/usr/bin/iceweasel"
		FLAGS="${BROWSER_HOMEPAGE}"
		;;
	*)
		echo "E: Invalid browser: ${BROWSER_APPLICATION}, exiting..."
		exit 1
		;;
esac

if [ -x "${APP}" ]
then
	${APP} ${FLAGS}
else
	echo "E: Cannot start browser: ${APP} ${FLAGS}!"
	exit 1
fi
