#!/bin/sh

# Configure desktop

BACKGROUND_IMAGE="/usr/share/digabi/proprietary/background.svg"
MENU_ICON="/usr/share/digabi/proprietary/digabi.svg"



# Configure XFCE4 settings
XFCONF_BIN="/usr/bin/xfconf-query"
XFCONF_FLAGS="-n"
XFWM_THEME="Radiance-Orange"

if [ -x "${XFCONF_BIN}" ]
then
    # Single color
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/backdrop/screen0/monitor0/color-style" -t "int" -s 0
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/backdrop/screen0/monitor1/color-style" -t "int" -s 0

    # Color from background.svg
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/backdrop/screen0/monitor0/color1" -t "uint" -s 9509 -t "uint" -s 17733 -t "uint" -s 29298 -t "uint" -s 65535
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/backdrop/screen0/monitor1/color1" -t "uint" -s 9509 -t "uint" -s 17733 -t "uint" -s 29298 -t "uint" -s 65535

    # Centered
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/backdrop/screen0/monitor0/image-style" -t "int" -s 0
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/backdrop/screen0/monitor1/image-style" -t "int" -s 0

    # Our custom image
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/backdrop/screen0/monitor0/image-path" -t "string" -s "${BACKGROUND_IMAGE}"
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/backdrop/screen0/monitor0/last-image" -t "string" -s "${BACKGROUND_IMAGE}"
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/backdrop/screen0/monitor0/last-single-image" -t "string" -s "${BACKGROUND_IMAGE}"
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/backdrop/screen0/monitor1/image-path" -t "string" -s "${BACKGROUND_IMAGE}"
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/backdrop/screen0/monitor1/last-image" -t "string" -s "${BACKGROUND_IMAGE}"
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/backdrop/screen0/monitor1/last-single-image" -t "string" -s "${BACKGROUND_IMAGE}"

    # Hide filesystem from desktop
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/desktop-icons/file-icons/show-filesystem" -t "bool" -s "false"

    # Hide home
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/desktop-icons/file-icons/show-home" -t "bool" -s "false"

    # Hide removable drives
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/desktop-icons/file-icons/show-removable" -t "bool" -s "false"

    # Hide trash
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/desktop-icons/file-icons/show-trash" -t "bool" -s "false"

    # Resize icons (48x48)
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/desktop-icons/icon-size" -t "int" -s 48

    # Hide window list
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-desktop" -p "/windowlist-menu/show" -t "bool" -s "false"

    # Set custom image for menu
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-panel" -p "/plugins/plugin-1/button-icon" -t "string" -s "${MENU_ICON}"

    # Hide suspend & hibernate from log-out window
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-session" -p "/shutdown/ShowSuspend" -t "bool" -s "false"
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-session" -p "/shutdown/ShowHibernate" -t "bool" -s "false"

    # Set default theme
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xsettings" -p "/Net/ThemeName" -t "string" -s "${XFWM_THEME}"

    # Set workspace count
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfwm4" -p "/general/workspace_count" -t "int" -s 1

    # Show shutdown button instead of logout window
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-panel" -p "/plugins/plugin-2/first-action" -t "int" -s 3

    # Toggle compositing on
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfwm4" -p "/general/use_compositing" -t "bool" -s "true"

    # Show shadows
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfwm4" -p "/general/show_dock_shadow" -t "bool" -s "true"
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfwm4" -p "/general/show_frame_shadow" -t "bool" -s "true"
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfwm4" -p "/general/show_popup_shadow" -t "bool" -s "true"

    # Transparent window when moving or resizing
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfwm4" -p "/general/move_opacity" -t "int" -s 90
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfwm4" -p "/general/resize_opacity" -t "int" -s 90

    # Blink urgent windows
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfwm4" -p "/general/urgent_blink" -t "bool" -s "true"

    # Antialiasing
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xsettings" -p "/xsettings/Xft/Antialias" -t "int" -s 1
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xsettings" -p "/xsettings/Xft/HintStyle" -t "string" -s "hintmedium"

    # Prettier notifications
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-notifyd" -p "/xfce4-notifyd/theme" -t "string" -s "Smoke"
fi
