#!/bin/sh

set -e

SOURCES_FILE="/etc/apt/sources.list.d/digabi.list"
SOURCES_URL="http://digabi.fi/s/digabi.list"
WGET_BIN="/usr/bin/wget"

if [ ! -f "${SOURCES_FILE}" ]
then
	${WGET_BIN} -O "${SOURCES_FILE}" "${SOURCES_URL}"
fi
