#!/bin/sh

set -e

COMMAND="$1"

if [ -z "${COMMAND}" ]
then
	echo "Missing command!"
	echo "Usage: $0 <command>"
	exit 1
fi

DIGABI_SCRIPT_LIBRARY="/usr/lib/digabi/scripts"

COMMAND_FILE="${DIGABI_SCRIPT_LIBRARY}/${COMMAND}"

if [ -x "${COMMAND_FILE}" ]
then
	exec "${COMMAND_FILE}"
else
	echo "Invalid command: ${COMMAND}, exiting..."
	exit 1
fi

