#!/bin/sh

set -e

CHANGELOG_FILE="changelog"
DCH_BIN="/usr/bin/dch"

if [ ! -f "${CHANGELOG_FILE}" ]
then
	echo "Changelog file not found (changelog). Exiting..."
	exit 1
fi

if [ ! -x "${DCH_BIN}" ]
then
	echo "dch command not found, exiting..."
	exit 1
fi

${DCH_BIN} -c changelog --distribution stable -i
