#!/bin/sh

# this script is part of digabi-dev package
#
# (c) 2013 Ville Korhonen <ville.korhonen@ylioppilastutkinto.fi>
# GPLv3

if [ -f /etc/digabirc ]
then
    . /etc/digabirc
fi

if [ -f $HOME/.digabirc ]
then
    . $HOME/.digabirc
fi

if [ -f .digabirc ]
then
    . .digabirc
fi

while [ "$1" = "-*" ]
do
    case "$1" in
        -h|--help|-\?)
            show_help
            exit 0
        ;;
        -c|--config)
            if [[ $# > 1 ]]
            then
                config_file="$2"
                shift 2
            else
                echo "--config requires an argument" 1>&2
                exit 1
            fi
        ;;
        --)
            shift
            break
        ;;
        -*)
            echo "Invalid option: $1" 1>&2
            show_help
            exit 1
        ;;
    esac
done

COMMAND="$1"

case "$COMMAND" in
    build)
    
    ;;
    sync)
    
    ;;
    test)
    
    ;;
esac
