#!/bin/sh

# this script is part of digabi-dev package
#
# (c) 2013 Ville Korhonen <ville.korhonen@ylioppilastutkinto.fi>
# GPLv3

# Read default values from example file
if [ -f /usr/share/digabi/examples/digabirc ]
then
    . /usr/share/digabi/examples/digabirc
fi

# Global config
if [ -f /etc/digabirc ]
then
    . /etc/digabirc
fi

# User-specific config
if [ -f $HOME/.digabirc ]
then
    . $HOME/.digabirc
fi

# Directory-specific config
if [ -f .digabirc ]
then
    . .digabirc
fi
