#!/bin/sh

#
# Tails: The Amnesic Incognito Live System
# Copyright © 2012 Tails developers <tails@boum.org>
# Copyright © 2014 Ylioppilastutkintolautakunta <digabi@ylioppilastutkinto.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Usage: ./release NEW_VERSION [ dev | SINCE_COMMITISH ]
# 
# If "dev" is supplied as the second argument, a development snapshot
# is done rather than a real release, i.e.:
#    * the --snapshot --auto options are passed to git-dch
#    * no commit or tag is created
# else, the second argument is passed to git-dch's --since option.

### source the configuration files

. config/digabi
if [ -e config/digabi.local ] ; then
   . config/digabi.local
fi

### init variables

NEW_VERSION="$1"
if [ "$2" = dev ]; then
   SNAPSHOT=yes
else
   SNAPSHOT=no
   SINCE="$2"
fi

### helper functions

fatal () {
   echo "Fatal: $@" >&2
   exit 2
}

### sanity checks

[ -n "${NEW_VERSION}" ] \
   || fatal "the new version must be supplied on the command-line."
[ -n "${DIGABI_DEV_FULLNAME}" ] \
   || fatal "DIGABI_DEV_FULLNAME must be set in config/digabi"
[ -n "${DIGABI_DEV_EMAIL}" ] \
   || fatal "DIGABI_DEV_EMAIL must be set in config/digabi"
[ -n "${DIGABI_DEV_KEYID}" ] \
   || fatal "DIGABI_DEV_KEYID must be set in config/digabi"
[ -x "`which git`" ] \
   || fatal "could not find git, please apt-get install git-core"
[ -x "`which git-dch`" ] \
   || fatal "could not find git-dch, please apt-get install git-buildpackage"

### main

export DEBFULLNAME="${DIGABI_DEV_FULLNAME}"
export DEBEMAIL="${DIGABI_DEV_EMAIL}"

# update the Changelog
echo "Updating debian/changelog from Git history..."
git-dch \
   `if [ ${SNAPSHOT} = yes ]; then echo '--snapshot --auto' ; fi` \
   `if [ ${SNAPSHOT} = no -a -n ${SINCE} ]; then echo "--release --since=${SINCE}" ; fi` \
   `if [ ${SNAPSHOT} = no -a -z ${SINCE} ]; then echo "--release --auto" ; fi` \
   --new-version="${NEW_VERSION}" \
   --ignore-branch \
   || fatal "git-dch failed."

# cleanup some parts of the changelog
perl -pi'' -e 's/\A  \[ IkiWiki::Plugin::po::change \]\n//' debian/changelog
perl -pi'' -e 's/\A  \* update[d]? PO file[s]?[.]?\n//' debian/changelog
perl -pi'' -e 's/\A  \* \n//' debian/changelog
perl -pi'' -e 's/\A  \[ 127\.0\.0\.1 \]\n//' debian/changelog
perl -pi'' -e 's/\A  \[ digabi \]\n//' debian/changelog
perl -pi'' -e 's/\A  \[ anonym \]\n//' debian/changelog
perl -pi'' -e 's/\A  \[ T\(A\)ILS developers \]\n//' debian/changelog
perl -pi'' -e 's/\A  \[ Tails developers \]\n//' debian/changelog
perl -pi'' -e 's/\A  \[ Tails \]\n//' debian/changelog
perl -pi'' -e 's/\A  \* Added a comment\n//' debian/changelog
perl -pi'' -e 's/\A  \* Added a comment:.*\n//' debian/changelog
perl -pi'' -e 's/\A  \* Remove spam\.\n//' debian/changelog
perl -pi'' -e 's/\A  \* todo\+\+\n//i' debian/changelog
perl -pi'' -e 's/\A  \* todo--\n//i' debian/changelog
perl -pi'' -e 's/\A  \* TODO update[.]?\n//i' debian/changelog
perl -pi'' -e 's/\A  \* Update ticket[.]?\n//i' debian/changelog
perl -pi'' -e 's/\A  \* Now pending[.]?\n//i' debian/changelog
perl -pi'' -e 's/\A  \* Done[.]?\n//i' debian/changelog
perl -pi'' -e 's/\A  \* Upcoming release\n//' debian/changelog

# commit and tag the release
# if [ "${SNAPSHOT}" = no ]; then
#    echo "Commit'ing debian/changelog..."
#    git commit -m "releasing version ${NEW_VERSION}" debian/changelog \
#       || fatal "failed to commit debian/changelog"
#    echo "Tagging new version..."
#    git tag -u "${DIGABI_DEV_KEYID}" -m "tagging version ${NEW_VERSION}" "${NEW_VERSION}"
# fi

echo "done."
