#!/bin/sh

# Configure XFCE4 settings

# Single color
xfconf-query -n -c xfce4-desktop -p /backdrop/screen0/monitor0/color-style -t int -s 0

# Color from background.svg
xfconf-query -n -c xfce4-desktop -p /backdrop/screen0/monitor0/color1 -t uint -s 9509 -t uint -s 17733 -t uint -s 29298 -t uint -s 65535

# Centered
xfconf-query -n -c xfce4-desktop -p /backdrop/screen0/monitor0/image-style -t int -s 1

# Our custom image
xfconf-query -n -c xfce4-desktop -p /backdrop/screen0/monitor0/image-path -t string -s /usr/share/digabi/proprietary/background.svg
xfconf-query -n -c xfce4-desktop -p /backdrop/screen0/monitor0/last-image -t string -s /usr/share/digabi/proprietary/background.svg
xfconf-query -n -c xfce4-desktop -p /backdrop/screen0/monitor0/last-single-image -t string -s /usr/share/digabi/proprietary/background.svg

# Hide filesystem from desktop
xfconf-query -n -c xfce4-desktop -p /desktop-icons/file-icons/show-filesystem -t bool -s false

# Hide home
xfconf-query -n -c xfce4-desktop -p /desktop-icons/file-icons/show-home -t bool -s false

# Hide removable drives
xfconf-query -n -c xfce4-desktop -p /desktop-icons/file-icons/show-removable -t bool -s false

# Hide trash
xfconf-query -n -c xfce4-desktop -p /desktop-icons/file-icons/show-trash -t bool -s false

# Resize icons (64x64)
xfconf-query -n -c xfce4-desktop -p /desktop-icons/icon-size -t int -s 64

# Hide context menu
xfconf-query -n -c xfce4-desktop -p /desktop-menu/show -t bool -s false

# Hide window list
xfconf-query -n -c xfce4-desktop -p /windowlist-menu/show -t bool -s false

# Set custom image for menu
xfconf-query -n -c xfce4-panel -p /plugins/plugin-1/button-icon -t string -s /usr/share/digabi/proprietary/digabi_48x48.png

# Hide suspend & hibernate from log-out window
xfconf-query -n -c xfce4-session -p /shutdown/ShowSuspend -t bool -s false
xfconf-query -n -c xfce4-session -p /shutdown/ShowHibernate -t bool -s false
