#!/bin/sh

SIZES="1024x768 1280x1024 1600x1200 1920x1080 1920x1200"

if [ "$#" != "2" ]
then
	echo "Usage: $0 <source-file> <output-dir>"
	exit 1
fi

SOURCE_FILE="${1}"
OUTPUT_DIR="${2}"

if [ ! -f "${SOURCE_FILE}" ]
then
	echo "Source file: ${SOURCE_FILE} doesn't exist, exiting..."
	exit 1
fi

if [ ! -d "${OUTPUT_DIR}" ]
then
	mkdir -p "${OUTPUT_DIR}"
fi

for s in ${SIZES}
do
	OUTPUT_FILE="${OUTPUT_DIR}/$(echo ${SOURCE_FILE} |sed 's/\.svg/.png/')"
	echo "${OUTPUT_FILE}"
	#${CONVERT_BIN} -resize "${s}" "${SOURCE_FILE}" "${OUTPUT_FILE}"
done
