#!/bin/sh

set -e

#
# Initialiaze new Vagrant (Debian wheezy/jessie)
#
DIGABI_REPOSITORY_PATH="/vagrant/custom-packages/digabi-repository"

if [ -x "/vagrant/scripts/vagrant-local.sh" ]
then
    echo "I: Run local Vagrant customization scripts.."
    /vagrant/scripts/vagrant-local.sh
fi

#
# Prefer IPv4 over IPv6
#
echo "I: Prefer IPv4 over IPv6..."
sed -i -e 's/#\(precedence ::ffff:.*100\)/\1/' /etc/gai.conf
sysctl -w net.ipv6.conf.all.disable_ipv6=1

#
# Do not use virtual machine proxy before apt-cacher-ng is installed
# (From Tails)
#
if [ "$http_proxy" = "http://$(hostname -f):3142" ] &&
   ! [ -f /etc/apt-cacher-ng/acng.conf ]; then
    LOCAL_HTTP_PROXY="$http_proxy"
    http_proxy=''
fi

echo "I: Add Digabi repository..."
if [ -f "${DIGABI_REPOSITORY_PATH}/digabi.list" ]
then
    cp ${DIGABI_REPOSITORY_PATH}/digabi.list /etc/apt/sources.list.d/digabi.list
else
    wget -qO /etc/apt/sources.list.d/digabi.list https://digabi.fi/debian/digabi.list
fi
if [ -f "${DIGABI_REPOSITORY_PATH}/digabi.asc" ]
then
    apt-key add ${DIGABI_REPOSITORY_PATH}/digabi.asc
else
    wget -qO- https://digabi.fi/debian/digabi.asc | apt-key add -
fi

# If APT source exists, move it as default mirror (fixed problems w/ pbuilder)
if [ ! -f "/etc/apt/sources.list" ] &&  [ -f "/etc/apt/sources.list.d/jessie.list" ]
then
    echo "I: Use jessie.list as sources.list (default mirror)..."
    mv /etc/apt/sources.list.d/jessie.list /etc/apt/sources.list
fi

if [ -n "${DEBIAN_MIRROR}" ]
then
    echo "I: Configuring custom Debian mirror: ${DEBIAN_MIRROR}..."
    #_DEBMIR="$(echo ${DEBIAN_MIRROR} |sed 's/\./\\./g' |sed 's/\//\\\//g')"
    #sed -i "s/http\:\/\/ftp\.[[:alpha:]][[:alpha:]]\.debian\.org\/debian\/${_DEBMIR}/g" /etc/apt/sources.list
    sed -i "s,http://ftp.[[:alpha:]][[:alpha:]].debian.org/debian,${DEBIAN_MIRROR},g" /etc/apt/sources.list
else
    echo "I: Using pre-configured Debian mirror."
fi

echo "I: Configure APT: do not install recommends..."
cat << EOF >/etc/apt/apt.conf.d/99-no-recommends
APT::Install-Recommends "false";
APT::Install-Suggests "false";
EOF

install -o root -g root -m 755 /vagrant/provision/assets/build-dos /usr/local/bin

echo "I: Update package lists..."
apt-get -qy update

echo "I: Install apt-cacher-ng..."
DEBIAN_FRONTEND=noninteractive apt-get -y install apt-cacher-ng

# Install custom configuration for apt-cacher-ng and restart
#install -o root -g root -m 644 /vagrant/provision/assets/acng.conf /etc/apt-cacher-ng/acng.conf
#service apt-cacher-ng restart

# Restore local HTTP proxy if needed
if [ "$LOCAL_HTTP_PROXY" ]; then
    http_proxy="$LOCAL_HTTP_PROXY"
fi

echo "I: Upgrade build system..."
DEBIAN_FRONTEND=noninteractive apt-get -qy dist-upgrade

echo "I: Install digabi-dev, rsync..."
DEBIAN_FRONTEND=noninteractive apt-get -o "Acquire::http::Pipeline-Depth=10" -qy install digabi-dev rsync
