# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1374674570);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1374674690);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 81920);
user_pref("browser.migration.version", 7);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.startup.homepage", "https://digabi.fi/");
user_pref("browser.startup.homepage_override.buildID", "20130626024843");
user_pref("browser.startup.homepage_override.mstone", "17.0.7");
user_pref("browser.syncPromoViewsLeft", 2);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "langpack-fi%40iceweasel.mozilla.org:17.0.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:17.0.7");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"langpack-fi@iceweasel.mozilla.org\":{\"descriptor\":\"/usr/lib/iceweasel/extensions/langpack-fi@iceweasel.mozilla.org.xpi\",\"mtime\":1372207220000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/iceweasel/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1374673866000}}}]");
user_pref("extensions.lastAppVersion", "17.0.7");
user_pref("extensions.lastPlatformVersion", "17.0.7");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 3004);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.rememberSignons", false);
user_pref("toolkit.startup.last_success", 1374674569);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1377266572);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
