#!/bin/sh

# Configure desktop

BACKGROUND_IMAGE="/usr/share/digabi/proprietary/background.svg"
MENU_ICON="/usr/share/digabi/proprietary/digabi.svg"



# Configure XFCE4 settings
XFCONF_BIN="/usr/bin/xfconf-query"
XFCONF_FLAGS="-n"

if [ -x "${XFCONF_BIN}" ]
then
    # Set custom image for menu
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-panel" -p "/plugins/plugin-1/button-icon" -t "string" -s "${MENU_ICON}"

    # Show shutdown button instead of logout window
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-panel" -p "/plugins/plugin-2/first-action" -t "int" -s 3

    # Prettier notifications
    ${XFCONF_BIN} ${XFCONF_FLAGS} -c "xfce4-notifyd" -p "/theme" -t "string" -s "Smoke"
    
fi

