#!/bin/sh

# Helper for building Linux kernel
# (c) 2013,2014 Ville Korhonen <ville.korhonen@ylioppilastutkinto.fi>

HELPERS="$(dirname $0)/_helpers" ; if [ -f "${HELPERS}" ] ; then . ${HELPERS} ; else echo "E: Script helpers (${HELPERS}) not found, exiting." ; exit 1 ; fi

if [ ! -f .config ]
then
    error "No kernel .config found, exiting..."
    exit 1
fi

if [ -f .revision ]
then
    REVISION="$(head -n1 .revision)"
else
    echo -n "Revision number: "
    read REVISION
#    REVISION="1"
fi

REVISION="$(echo $REVISION |awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')"
echo $REVISION >.revision

_REVISION="$(date +%Y%m%d%H%M%S)-${REVISION}"

info "Cleaning build directories..."
fakeroot make-kpkg clean

_PARALLEL="$(cat /proc/cpuinfo |egrep ^processor |tail -n 1 |awk '{print $3}' |awk -F. '{$NF = $NF + 2;} 1' | sed 's/ /./g')"

info "Building revision ${REVISION}..."
fakeroot make-kpkg -j${_PARALLEL} --initrd --revision "${_REVISION}" kernel_image kernel_headers kernel_source 2>&1 |tee build.log

TIMESTAMP="$(date +%s)"
CONFIG_TARGET="../linux-$(make kernelversion)-${_REVISION}_${TIMESTAMP}.config"

cp .config "${CONFIG_TARGET}"
