#!/bin/sh

# Build all custom packages
#
# (c) 2013 Ville Korhonen <ville.korhonen@ylioppilastutkinto.fi>
# GPLv3

HELPERS="$(dirname $0)/_helpers" ; if [ -f "${HELPERS}" ] ; then . ${HELPERS} ; else echo "E: Script helpers (${HELPERS}) not found, exiting." ; exit 1 ; fi

CUSTOM_PACKAGE_DIR="custom-packages"

if [ ! -d "${CUSTOM_PACKAGE_DIR}" ]
then
    error "Custom package dir ${CUSTOM_PACKAGE_DIR} not found. Exiting..."
    exit 1
fi

cd "${CUSTOM_PACKAGE_DIR}"

for pkg in `ls`
do
    if [ -d "${pkg}" ]
    then
        cd "${pkg}"
        `digabi os build-package` || warning "Didn't build ${pkg}."
        debs="$(ls ${pkg}_*_*.deb 2>/dev/null)"
        if [ -z "${debs}" ]
            then
            warning "No debs found for package ${pkg}."
        else
            for deb in $debs
            do
                debug "Moving file ${deb}..."
                mv "${deb}" ..
            done
        fi
        cd ..
    fi
done

cd ..

