#!/bin/sh

set -ex

. $(dirname $0)/_jenkins

trap cleanup EXIT

make dist DIGABI_DEBUG="${DIGABI_DEBUG}" COMMIT="${COMMIT}" ROOT_PASSWORD="${ROOT_PASSWORD}" ARCH="${ARCH}" DEBIAN_MIRROR="${DEBIAN_MIRROR}" http_proxy="${PROXY}" BUILD_TAG="${BUILD_TAG}"
