#!/bin/sh

set -xe

. $(dirname $0)/_jenkins

cd vagrant

rm -f *.box

vagrant up
vagrant ssh -c 'sudo apt-get clean'
vagrant ssh -c 'sudo dd if=/dev/zero of=/EMPTY bs=1M ; sudo rm -f /EMPTY'
vagrant halt
vagrant package --output "dos-builder-$(date +%Y%m%d%H%M%S).box"
vagrant destroy -f
