# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Add vagrant/lib to Ruby path
$:.unshift File.expand_path('../lib', __FILE__)

require 'vagrant_verified_download'
require 'digabi_build_settings'

if ENV['DIGABI_BUILD_MEM']
  mem_size = ENV['DIGABI_BUILD_MEM']
elsif ENV['DIGABI_RAM_BUILD']
  mem_size = VM_MEMORY_FOR_RAM_BUILDS
else
  mem_size = VM_MEMORY_FOR_DISK_BUILDS
end
cpus = ENV['DIGABI_BUILD_CPUS']

if ENV['DIGABI_NETWORK_TYPE']
  network_type = ENV['DIGABI_NETWORK_TYPE']
end

if ENV['DIGABI_NETWORK_HOST_DEV']
  network_host_dev = ENV['DIGABI_NETWORK_HOST_DEV']
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian-jessie64"

  config.vm.box_url = "https://cdn.ypcs.fi/vagrant/metadata.json"

  config.vm.provision "shell", inline: "sudo http_proxy='#{ENV['http_proxy']}' DEBIAN_MIRROR='#{ENV['DEBIAN_MIRROR']}' /vagrant/provision/setup-dos-builder"
  config.vm.synced_folder '../.git', '/digabi-os.git'

  if network_type == 'bridged'
    if network_host_dev
      config.vm.network "public_network", bridge: network_host_dev
    else
      config.vm.network "public_network"    
    end
#  else
#    config.vm.network "private_network", type: "dhcp"
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', mem_size]
    vb.customize ['modifyvm', :id, '--cpus', cpus] unless cpus.nil?
    vb.customize ['modifyvm', :id, '--ioapic', 'on']
    vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
  end

  config.vm.provider :vmware_workstation do |vmw, override|
    vmw.vmx['memsize'] = mem_size
    vmw.vmx['numvcpus'] = cpus unless cpus.nil?
  end

  config.vm.provider :vmware_fusion do |vmw, override|
    vmw.vmx['memsize'] = mem_size
    vmw.vmx['numvcpus'] = cpus unless cpus.nil?
  end
end
