#!/bin/sh

# Build all custom packages
#
# (c) 2013 Ville Korhonen <ville.korhonen@ylioppilastutkinto.fi>
# GPLv3

CUSTOM_PACKAGE_DIR="custom-packages"

cd "${CUSTOM_PACKAGE_DIR}"

for pkg in `ls`
do
    if [ -d "${pkg}" && -f "${pkg}/debian/control" ]
    then
        cd "${pkg}"
        equivs-build debian/control
        mv *.deb ..
        cd ..
    fi
done

cd ..

