#!/bin/sh

# Build all custom packages
#
# (c) 2013 Ville Korhonen <ville.korhonen@ylioppilastutkinto.fi>
# GPLv3

CUSTOM_PACKAGE_DIR="custom-packages"

if [ ! -d "${CUSTOM_PACKAGE_DIR}" ]
then
	echo "E: Custom package dir ${CUSTOM_PACKAGE_DIR} not found. Exiting..."
	exit 1
fi

cd "${CUSTOM_PACKAGE_DIR}"

for pkg in `ls`
do
    if [ -d "${pkg}" ]
    then
        cd "${pkg}"
        digabi build-package
        debs="$(ls ${pkg}_*_*.deb 2>/dev/null)"
        if [ -z "${debs}" ]
            then
            echo "W: No debs found for package ${pkg}."
        else
            for deb in $debs
            do
                echo "I: Moving file ${deb}..."
                mv "${deb}" ..
            done
        fi
        cd ..
    fi
done

cd ..

