#!/bin/sh

set -e

# TODO: Check if file basename `dirname $0` exists (file which name is same as dir), if, build it
# TODO: Allow building packages w/ $0 <package-name>

if [ -f "debian/control" ]
then
    echo "I: Building package. ($PWD)"
	equivs-build debian/control 1>/dev/null
else
	echo "E: Package control file debian/control not found. ($PWD)"
	exit 1
fi
