#!/bin/sh

set +e

ISOFILE="$1"

if [ -z "${ISOFILE}" ]
then
    echo "Usage: $0 <isofile>"
    exit 1
fi

if [ ! -f "${ISOFILE}" ]
then
    echo "ISO file ${ISOFILE} not found, exiting..."
    exit 1
fi

warning() {
	echo "W: $@"
}

error() {
	echo "E: $@"
}

debug() {
	echo "D: $@"
}

info() {
	echo "I: $@"
}

TEMPDIR="$(mktemp -d)"

ISO_MOUNT="${TEMPDIR}/iso"
SQFS_MOUNT="${TEMPDIR}/sqfs"

mkdir -p "${ISO_MOUNT}"
mkdir -p "${SQFS_MOUNT}"

# Init
info "Mounting ISO (${ISOFILE}) to ${ISO_MOUNT}..."
/bin/mount -t iso9660 -o ro,loop ${ISOFILE} ${ISO_MOUNT}

info "Mounting SquashFS to ${SQFS_MOUNT}..."
/bin/mount -t squashfs -o ro ${ISO_MOUNT}/live/filesystem.squashfs ${SQFS_MOUNT}

# Do the tricks...

info "Testijuttu jeejeeejee"

info "Check image size..."
info "Image size: $(/usr/bin/stat --format=%s ${ISOFILE}) bytes."

info "Search for SUID/SGID binaries..."
{
	SUID_SGID="$(/usr/bin/find ${SQFS_MOUNT} -type f \( -perm +4000 -o -perm +2000 \) -print 2>/dev/null |xargs)"
	for s in ${SUID_SGID}
	do
		warning "SUID/SGID: $(echo $s |sed "s,${SQFS_MOUNT},,g")"
	done
}

debug "TODO: Require whitelisting for SUID/SGID binaries and their packages"

debug "TODO: Search for world writable files/directories"
{
	find ${SQFS_MOUNT} -xdev -perm +o=w ! \( -type d -perm +o=t \) ! -type l -print
}

debug "TODO: Check that required packages are installed"
debug "TODO: Check that unused users have no shells"
debug "TODO: Check that root user is locked"
debug "TODO: Check enabled services"
debug "TODO: Check crontab"

info "Find all TODO/FIXME notes..."
# Find from both, ISO and SquashFS
{
	/bin/egrep -R "(TODO|FIXME)" ${TEMPDIR}
}



debug "TODO: Check sysctl values"

# Stop...
info "Unmounting SquashFS (${SQFS_MOUNT})..."
/bin/umount -l ${SQFS_MOUNT}

info "Unmounting ISO (${ISO_MOUNT})..."
/bin/umount -l ${ISO_MOUNT}
