#!/bin/sh

set -e

HELPERS="$(dirname $0)/_helpers" ; if [ -f "${HELPERS}" ] ; then . ${HELPERS} ; else echo "E: Script helpers (${HELPERS}) not found, exiting." ; exit 1 ; fi

COMMAND="$1"

if [ -z "${COMMAND}" ]
then
    echo "Usage: $0 <command>"
    exit 1
fi

REPO_URL="https://github.com/digabi/digabi-os"
REPO_PATH="digabi-os"

# TODO: If currently in digabi-live, do not clone (use current dir)
# TODO: Check that git repo is right one (first commit?)
# TODO: Show changelog between two versions (default: latest tag -> latest-1 tag), "Changes in XX.XX.YY"
# TODO: Add other commands... clone repository, create patch from customizations, ...
# TODO: Create tool or queueing DOS builds (w/ 

case "${COMMAND}" in
	fetch)
		COMMIT="$2"
		BRANCH="$3"

		if [ -z "${COMMIT}" ]
		then
			echo "Usage: $0 fetch <commit-id> <branch-to-be-created>"
			echo "Example: $0 fetch 24b3e6 mytestbuild"
			exit 1
		fi


		if [ -d "${PWD}/${REPO_PATH}" ]
		then
			git pull "${REPO_URL}"
		else
			git clone "${REPO_URL}" "${REPO_PATH}"
		fi
		cd ${REPO_PATH}

		git co -b ${BRANCH} ${COMMIT}
		info "Successfully checked out commit ${COMMIT}, created branch ${BRANCH}."
		;;
	*)
	    CMD="$(dirname $(readlink -f $0))/_os/${COMMAND}"
	    if [ -x "${CMD}" ]
	    then
		${CMD} $@
	    else
	   		error "Invalid command: ${COMMAND}."
	    	exit 1
	    fi
		;;
esac
