#!/bin/sh

# Download and patch kernel sources
# GPLv2
#
# (c) 2013 The Matriculation Examination Board of Finland / Ylioppilastutkintolautakunta
# Author: Ville Korhonen <ville.korhonen@ylioppilastutkinto.fi>

set -e

KERNEL_VERSION="3.2.50"
AUFS_VERSION="3.2"
GRSECURITY_VERSION="2.9.1"


# Configure apps
BASENAME_BIN="/usr/bin/basename"

ECHO_BIN="/bin/echo"

WGET_BIN="/usr/bin/wget"
WGET_FLAGS="-q"

TAR_BIN="/bin/tar"
TAR_FLAGS="-xJf"

PATCH_BIN="/usr/bin/patch"
PATCH_FLAGS="-s -p1"

CP_BIN="/bin/cp"
CP_FLAGS="-R"

MOVE_BIN="/bin/mv"

UNZIP_BIN="/usr/bin/unzip"
UNZIP_FLAGS="-uq"

DATE_BIN="/bin/date"
DATE_FORMAT="+%Y%m%d%H%M%S"

BINARIES="${BASENAME_BIN} ${ECHO_BIN} ${WGET_BIN} ${TAR_BIN} ${PATCH_BIN} ${CP_BIN} ${UNZIP_BIN} ${MOVE_BIN} ${DATE_BIN}"
for b in ${BINARIES}
do
	if [ ! -x "${b}" ]
	then
		echo "Command `${b}` not found, exiting..."
		exit 1
	fi
done


# Linux Kernel <https://kernel.org/>
KERNEL_URL="https://www.kernel.org/pub/linux/kernel/v3.x/linux-${KERNEL_VERSION}.tar.xz"
KERNEL_ARCHIVE_FILE="$(${BASENAME_BIN} ${KERNEL_URL})"
KERNEL_SOURCE_DIR="$(${ECHO_BIN} ${KERNEL_ARCHIVE_FILE} |sed 's/\.tar\.xz//')"

# Grsecurity <https://grsecurity.net/>
GRSECURITY_PATCH_FILE="grsecurity-${GRSECURITY_VERSION}-${KERNEL_VERSION}.patch"
GRSECURITY_URL="https://github.com/digabi/digabi-misc/raw/master/${GRSECURITY_PATCH_FILE}"
#GRSECURITY_PATCH_FILE="$(${BASENAME_BIN} ${GRSECURITY_URL})"

# AUFS, Advanced Union Filesystem <http://aufs.sourceforge.net/>
AUFS_URL="https://github.com/digabi/aufs3-standalone/archive/aufs${AUFS_VERSION}.zip"
AUFS_ARCHIVE_FILE="$(${BASENAME_BIN} ${AUFS_URL})"
AUFS_SOURCE_DIR="aufs3-standalone-aufs${AUFS_VERSION}" 			# TODO: Extract directory name from GitHub repo + branch

DIGABI_CONFIG_URL="https://github.com/digabi/digabi-live/raw/master/custom-packages/linux-image-ytl/linux.config"

if [ -f "${KERNEL_ARCHIVE}" ]
then
	echo "Kernel already downloaded, skipping..."
else
	echo "Download kernel..."
	${WGET_BIN} ${WGET_FLAGS} "${KERNEL_URL}"
fi
if [ -f "${GRSECURITY_PATCH_FILE}" ]
then
	echo "grsecurity patch already downloaded, skipping..."
else
	echo "Download grsecurity patch..."
	${WGET_BIN} ${WGET_FLAGS} "${GRSECURITY_URL}"
fi
if [ -f "${AUFS_ARCHIVE_FILE}" ]
then
	echo "AUFS patch already downloaded, skipping..."
else
	echo "Download AUFS3 patch..."
	${WGET_BIN} ${WGET_FLAGS} "${AUFS_URL}"
fi

if [ -d "${KERNEL_SOURCE_DIR}" ]
then
	TIMESTAMP="$(${DATE_BIN} ${DATE_FORMAT})"
	KERNEL_OLD_DIR="${KERNEL_SOURCE_DIR}.${TIMESTAMP}"
	echo "Kernel archive already extracted, moving old to ${KERNEL_OLD_DIR}..."
	${MOVE_BIN} "${KERNEL_SOURCE_DIR}" "${KERNEL_OLD_DIR}"
fi
echo "Extracting kernel..."
${TAR_BIN} ${TAR_FLAGS} "${KERNEL_ARCHIVE_FILE}"

if [ -d "${AUFS_SOURCE_DIR}" ]
then
	echo "AUFS3 archive already extracted, skipping..."
else
	echo "Extracting AUFS3 sources..."
	${UNZIP_BIN} ${UNZIP_FLAGS} "${AUFS_ARCHIVE_FILE}"
fi

cd "${KERNEL_SOURCE_DIR}"
echo "Patching kernel sources..."
AUFS_PATCHES="kbuild base standalone"
for p in ${AUFS_PATCHES}
do
	echo "Applying AUFS3 patch: ${p}..."
	${PATCH_BIN} ${PATCH_FLAGS} < "../${AUFS_SOURCE_DIR}/aufs3-${p}.patch"
done
AUFS_FILES="fs Documentation"
for f in ${AUFS_FILES}
do
	echo "Copying required files from AUFS3 source: ${f}..."
	${CP_BIN} ${CP_FLAGS} "../${AUFS_SOURCE_DIR}/${f}" .
done
${CP_BIN} "../${AUFS_SOURCE_DIR}/include/linux/aufs_type.h" ./include/linux/

echo "Applying grsecurity patch..."
${PATCH_BIN} ${PATCH_FLAGS} < "../${GRSECURITY_PATCH_FILE}"

echo "Fetch current config from ${DIGABI_CONFIG_URL}..."
${WGET_BIN} ${WGET_FLAGS} -O .config "${DIGABI_CONFIG_URL}"

echo
echo "Done!"
