#!/bin/sh

set -e

BUILD_VERSION="${1}"
case "${BUILD_VERSION}" in
    dev*)
        BUILD_VERSION="dev"
        shift 1
        ;;
    dist*)
        BUILD_VERSION="dist"
        shift 1
        ;;
    *)
        BUILD_VERSION="dev"
esac

VERSION="$(${PWD}/scripts/version.helper ${BUILD_VERSION})"
echo "I: Building version ${VERSION}..."

BUILD_HOOKS="$(ls ${PWD}/scripts/*.build)"

if [ -n "${BUILD_HOOKS}" ]
then
    echo "I: Executing build hooks..."
fi

for hook in ${BUILD_HOOKS}
do
    hook_base="$(basename ${hook})"
    if [ -x "${hook}" ]
    then
        echo "I: Executing hook ${hook_base}..."
        ${hook}
    else
        echo "W: Non-executable hook ${hook_base}."
    fi
done

lb build noauto "${@}" 2>&1 | tee build.log
