#!/bin/sh

set -e

ARCHITECTURE="i386"
#ARCHITECTURE="$(dpkg --print-architecture)"

#case "${ARCHITECTURE}" in
#    amd64)
#        _LINUX_FLAVOURS="amd64"
#        _SOURCE="false"
#        ;;
#    i386)
#        _LINUX_FLAVOURS="486 686-pae"
#        _SOURCE="false"
#        ;;
#    *)
#	_LINUX_FLAVOURS="686-pae"
#	_SOURCE="false"
#esac

_LINUX_FLAVOURS="686-pae"
#_LINUX_FLAVOURS="ytl"
_SOURCE="false"

ARCHIVE_AREAS="main contrib non-free"
DISTRIBUTION="jessie"

if [ -z "${REPOSITORY}" ] ; then
    REPOSITORY="http://ftp.fi.debian.org/debian/"
fi

BOOTAPPEND_LIVE="boot=live config quiet splash security=apparmor"
ISO_PUBLISHER="Ylioppilastutkintolautakunta ; https://digabi.fi ; digabi@ylioppilastutkinto.fi"
ISO_VOLUME="dos-$(./scripts/version.helper notime nobuild shortver |cut -b-27)"

#if [ -z "${APT_PROXY}" ]
#then
#    APT_PROXY="http://localhost:3142/"
#fi

lb config noauto \
    --clean \
    --ignore-system-defaults \
    --architecture "${ARCHITECTURE}" \
    --archive-areas "${ARCHIVE_AREAS}" \
    --distribution "${DISTRIBUTION}" \
    --linux-flavour "${_LINUX_FLAVOURS}" \
    --linux-packages "linux-image" \
    --apt-indices "false" \
    --apt-recommends "false" \
    --bootappend-live "${BOOTAPPEND_LIVE}" \
    --iso-volume "${ISO_VOLUME}" \
    --iso-publisher "${ISO_PUBLISHER}" \
    --memtest "none" \
    --source "${_SOURCE}" \
    --apt-source-archives "${_SOURCE}" \
    --parent-mirror-bootstrap "${REPOSITORY}" \
    --parent-mirror-binary "${REPOSITORY}" \
    --mirror-bootstrap "${REPOSITORY}" \
    --mirror-chroot "${REPOSITORY}" \
    --mirror-binary "${REPOSITORY}" \
    --security "true" \
    --win32-loader "true" \
	"${@}"
