#!/bin/sh

set -e

ARCHITECTURE="i386"
#ARCHITECTURE="$(dpkg --print-architecture)"

case "${ARCHITECTURE}" in
    amd64)
        _LINUX_FLAVOURS="amd64"
        _SOURCE="false"
        ;;
    i386)
        _LINUX_FLAVOURS="486 686-pae"
        _SOURCE="false"
        ;;
esac


DISTRIBUTION="wheezy"
REPOSITORY="http://ftp.fi.debian.org/debian/"

LOCALES="fi_FI.UTF-8,sv_SE.UTF-8,en_US.UTF-8,sv_FI.UTF-8"
KEYBOARD_LAYOUT="fi"
HOSTCONFIG="hostname=digabi username=digabi"
BOOTAPPEND_LIVE="boot=live config locales=${LOCALES} keyboard-layouts=${KEYBOARD_LAYOUT} quiet splash ${HOSTCONFIG} security=apparmor"

lb config noauto \
    --clean \
    --ignore-system-defaults \
    --architecture "${ARCHITECTURE}" \
    --archive-areas "main" \
    --apt-http-proxy "http://10.0.2.2:3142/" \
    --distribution "${DISTRIBUTION}" \
    --linux-flavour "$(_LINUX_FLAVOURS)" \
    --linux-packages "linux-image linux-headers" \
    --apt-indices false \
    --apt-recommends false \
    --bootappend-live "${BOOTAPPEND_LIVE}" \
    --iso-volume "digabi $(date +%Y%m%d-%H:%M)" \
    --iso-publisher "Ylioppilastutkintolautakunta / digabi ; http://digabi.fi ; digabi@digabi.fi" \
    --memtest none \
    --source "$(_SOURCE)" \
    --parent-mirror-bootstrap $REPOSITORY \
    --parent-mirror-binary $REPOSITORY \
    --mirror-bootstrap $REPOSITORY \
    --mirror-chroot $REPOSITORY \
    --mirror-binary $REPOSITORY \
	"${@}"
