#!/bin/sh

set -e

ARCHITECTURE="i386"

case "$(dpkg --print-architecture)" in
    amd64)
        _LINUX_FLAVOURS="amd64"
        _SOURCE="false"
        ;;
    i386)
        _LINUX_FLAVOURS="486 686-pae"
        _SOURCE="false"
        ;;
esac


DISTRIBUTION="jessie"
REPOSITORY="http://ftp.fi.debian.org/debian/"

lb config noauto \
    --clean \
    --ignore-system-defaults \
    --architecture "${ARCHITECTURE}" \
    --archive-areas "main" \
    --apt-http-proxy "http://localhost:3142/" \
    --distribution "${DISTRIBUTION}" \
    --linux-flavour "$(_LINUX_FLAVOURS)" \
    --linux-packages "linux-image linux-headers" \
    --apt-indices false \
    --apt-recommends false \
    --bootappend-live "boot=live config locales=fi_FI.UTF-8,sv_SE.UTF-8,en_US.UTF-8,sv_FI.UTF-8 keyboard-layouts=fi quiet splash hostname=digabi username=digabi" \
    --iso-volume "digabi $(date +%Y%m%d-%H:%M)" \
    --iso-publisher "Ylioppilastutkintolautakunta / digabi ; http://digabi.fi ; digabi@digabi.fi" \
    --memtest none \
    --source "$(_SOURCE)" \
    --parent-mirror-bootstrap $REPOSITORY \
    --parent-mirror-binary $REPOSITORY \
    --mirror-bootstrap $REPOSITORY \
    --mirror-chroot $REPOSITORY \
    --mirror-binary $REPOSITORY \
	"${@}"
