#!/bin/sh

IPTABLES="/sbin/iptables"

$IPTABLES -F
$IPTABLES -P INPUT DROP
$IPTABLES -P OUTPUT DROP
$IPTABLES -P FORWARD DROP

$IPTABLES -I INPUT -i lo -j ACCEPT
$IPTABLES -I INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
$IPTABLES -I OUTPUT -p tcp --dport 80 -j ACCEPT
$IPTABLES -I OUTPUT -p tcp --dport 443 -j ACCEPT
$IPTABLES -I OUTPUT -p udp --dport 53 -j ACCEPT
