#!/bin/sh

set -e

SOURCESLIST="/usr/share/doc/digabi-os-debug/digabi-os-debug.list" 

if [ ! -f "${SOURCESLIST}" ]
then
    echo "E: sources.list template is missing."
    exit 1
fi

if [ ! -w "/etc/apt/sources.list.d" ]
then
    echo "E: No permissions to add new sources.list."
    exit 1
fi

cp "${SOURCESLIST}" /etc/apt/sources.list.d/
apt-get update
DEBIAN_FRONTEND="noninteractive" apt-get -y upgrade
