#!/bin/sh

set -e

if [ -z "${CI_HOST}" ]
then
    CI_HOST="http://cimonitor"
fi

if [ -z "${ARCH}" ]
then
    ARCH="i386"
fi

if [ -z "${JOB}" ]
then
    if [ "${ARCH}" = "i386" ]
    then
        JOB="digabi-os build"
    elif [ "${ARCH}" = "amd64" ]
    then
        JOB="digabi-os build 64bit"
    else
        echo "E: Invalid architecture."
    fi
fi
FILENAME_XPATH="[ends-with%28.,%27iso%27%29]/text%28%29"

URL_BASE="${CI_HOST}/job/$(echo ${JOB} |sed 's/ /%20/g')/lastSuccessfulBuild"
ISO_NAME="$(wget -qO- ${URL_BASE}/api/xml?xpath=//fileName${FILENAME_XPATH})"

URL="${URL_BASE}/artifact/dist/${ISO_NAME}"

if [ -f "${ISO_NAME}" ]
then
    echo "E: Target file ${ISO_NAME} already exists, cancelling download."
    exit 1
fi

wget -O "${ISO_NAME}" "${URL}"
echo "I: Downloaded ${ISO_NAME} succesfully"
