#!/bin/sh

set -e

# Run browser with custom config

HELPERS="$(dirname $0)/_helpers" ; if [ -f "${HELPERS}" ] ; then . ${HELPERS} ; else echo "E: Script helpers (${HELPERS}) not found, exiting." ; exit 1 ; fi

BROWSER="$(digabi config get browser-browser)"

if [ -z "${BROWSER}" ]
then
    # TODO: Ask user, which browser should we use...
fi


HOMEPAGE="$(digabi config get browser-homepage)"

case "${BROWSER}" in
    chromium)
        /usr/bin/chromium # TODO: Add flags
        ;;
    firefox)
        /usr/bin/iceweasel # TODO: Add flags
        ;;
    *)
        echo "Unknown browser: ${BROWSER}, exiting..."
        exit 1
esac
