#!/bin/sh

set -e

COMMAND="$1"
KEY="$2"

# TODO: If --global, use /etc/digabi as configuration path, else use ~/.digabi

usage() {
    echo "Usage: $0 {get|set} <key> [value]"
}

if [ -z "${COMMAND}" ]
then
    echo "Command is missing..."
    usage
    exit 1
fi

if [ -z "${KEY}" ]
then
    echo "Key is missing..."
    usage
    exit 1
fi

case "${COMMAND}" in
    set)
    
        ;;
    get)
        ;;
    **)
        echo "Invalid command: ${COMMAND}, exiting..."
        exit 1
esac
