#!/bin/sh

set -e

# Handle Digabi configuration files

# Config files: /etc/digabi/* (global), ~/.config/digabi/* (user)
# Variable structure: APPNAME_KEYNAME, example: "BROWSER_HOMEPAGE"
# File naming: appname, example: "browser"
# File format: APPNAME_KEYNAME=VALUE, example: BROWSER_HOMEPAGE="http://digabi.fi/"

# Copyright 2014 Ylioppilastutkintolautakunta
# Author: Ville Korhonen <ville.korhonen@ylioppilastutkinto.fi>

COMMAND="$1"
if [ "$2" = "--global" ]
then
    GLOBAL="true"
    KEY="$3"
    shift
else
    KEY="$2"
fi

info() {
    echo "I: $@"
}

error() {
    echo "E: $@"
}

usage() {
    echo "Usage: $0 {get|set|source|conf-file|show} <key> [value]"
}

if [ -z "${COMMAND}" ]
then
    echo "Command is missing..."
    usage
    exit 1
fi

if [ -z "${KEY}" ]
then
    echo "Key is missing..."
    usage
    exit 1
fi
KEY="$(echo ${KEY} |tr '[:lower:]' '[:upper:]' |sed 's/-/_/g')"

if [ -z "${GLOBAL}" ]
then
    CONFIG_DIR="${XDG_CONFIG_HOME:=${HOME}/.config}/digabi"
else
    CONFIG_DIR="/etc/digabi/.digabi"
fi

APPNAME="$(echo ${KEY} |cut -d_ -f1 |tr '[:upper:]' '[:lower:]')"
CONFIG_FILE="${CONFIG_DIR}/${APPNAME}"

case "${COMMAND}" in
    set)
        # TODO: Set value
        ;;
    get)
        # TODO: Get value (or return default, if specified)
        ;;
    conf-file)
        echo "${CONFIG_FILE}"
        ;;
    source)
        if [ -f "${CONFIG_FILE}" ]
        then
            . "${CONFIG_FILE}"
        else
            error "Config file not found: ${CONFIG_FILE}."
            exit 1
        fi
        ;;
    show)
        if [ -f "${CONFIG_FILE}" ]
        then
            cat "${CONFIG_FILE}"
        else
            error "Config file not found: ${CONFIG_FILE}."
            exit 1
        fi
        ;;
    **)
        echo "Invalid command: ${COMMAND}, exiting..."
        exit 1
esac
