#!/bin/sh

set -e

# Prints out digabi version number

HELPERS="$(dirname $0)/_helpers" ; if [ -f "${HELPERS}" ] ; then . ${HELPERS} ; else echo "E: Script helpers (${HELPERS}) not found, exiting." ; exit 1 ; fi


VERSION_FILES="/var/lib/digabi/version /etc/digabi-version"

for f in ${VERSION_FILES}
do
    if [ -f "${f}" ]
    then
        VERSION_FILE="${f}"
        break
    fi
done

if [ ! -f "${VERSION_FILE}" ]
then
	error "No version number available."
	exit 1
fi

SHORT="$1"


if [ "x${SHORT}" = "xshort" ]
then
	VERSION="$(cat ${VERSION_FILE} |cut -d+ -f1)"
	GIT_COMMIT="$(cat ${VERSION_FILE} |cut -d- -f2 |cut -d_ -f1)"
	echo "${VERSION}"
	echo "${GIT_COMMIT}"
else
	VERSION="$(cat ${VERSION_FILE})"
	echo "Digabi Live ${VERSION}"
fi

